const cards = [
  // AUTOS
  {
    cat: ["autos"],
    name: "Carlos Tévez",
    detail: "Auto, Dual Patch e Numerada a /36",
    club: "Argentina",
    numbered: true,
    set: "Topps Argentina FansMall",
    price: 90,
    sold: false,
    badge: "Auto · Patch · /36",
    img: "images/tevez_front.jpg",
    back: "images/tevez_back.jpg",
    slug: "tevez"
  },
  {
    cat: ["autos"],
    name: "Andrea Pirlo",
    detail: "Signature Series · Auto",
    club: "Itália",
    numbered: false,
    set: "Panini Donruss 2024-25",
    price: 70,
    sold: false,
    badge: "Auto",
    img: "images/pirlo_front.jpg",
    back: "images/pirlo_back.jpg",
    slug: "pirlo"
  },
  {
    cat: ["autos"],
    name: "Diogo Jota",
    detail: "Auto",
    club: "Portugal",
    numbered: false,
    set: "International Ink Panini",
    price: 70,
    sold: false,
    badge: "Auto",
    img: "images/jota_front.jpeg",
    back: "images/jota_back.jpeg",
    slug: "jota"
  },
  {
    cat: ["autos"],
    name: "Matheus Nunes",
    detail: "Auto · /10",
    club: "Wolves",
    numbered: true,
    set: "Ultimate Leaf Soccer",
    price: 20,
    sold: false,
    badge: "Auto",
    img: "images/matheus10_front.jpeg",
    back: "images/matheus10_back.jpeg",
    slug: "matheus10"
  },
  {
    cat: ["autos"],
    name: "Matheus Nunes",
    detail: "Auto",
    club: "Portugal",
    numbered: false,
    set: "Topps Finest Road to UEFA Euro 2024",
    price: 15,
    sold: true,
    badge: "Auto",
    img: "images/matheus_front.jpeg",
    back: "images/matheus_back.jpeg",
    slug: "matheus"
  },
  {
    cat: ["autos"],
    name: "Hugo Félix",
    detail: "Auto · /35 · Rookie",
    club: "Benfica",
    numbered: true,
    set: "Leaf Rookie",
    price: 15,
    sold: false,
    badge: "Auto",
    img: "images/hugo_front.jpeg",
    back: "images/hugo_back.jpeg",
    slug: "hugo"
  },
  {
    cat: ["autos"],
    name: "Fábio Silva",
    detail: "Auto",
    club: "Las Palmas",
    numbered: false,
    set: "Panini La Liga Select 2024-25",
    price: 15,
    sold: true,
    badge: "Auto",
    img: "images/fabio_front.jpeg",
    back: "images/fabio_back.jpeg",
    slug: "fabio"
  },
  {
    cat: ["autos"],
    name: "Gonçalo Ramos",
    detail: "Auto · /75",
    club: "PSG",
    numbered: true,
    set: "Topps Finest 2024-25",
    price: 20,
    sold: false,
    badge: "Auto",
    img: "images/ramos75_front.jpeg",
    back: "images/ramos75_back.jpeg",
    slug: "ramos75"
  },
  {
    cat: ["autos"],
    name: "Carlos Forbs",
    detail: "Auto e Numerada a /7",
    club: "Manchester City",
    numbered: true,
    set: "Leaf Rookie",
    price: 20,
    sold: false,
    badge: "Auto · /7 · Rookie",
    img: "images/forbs_front.jpeg",
    back: "images/forbs_back.jpeg",
    slug: "forbs7"
  },
  {
    cat: ["autos"],
    name: "Joe Hart",
    detail: "Auto, Patch e Numerada a /199",
    club: "Inglaterra",
    numbered: true,
    set: "Panini Obsidian 2023-24",
    price: 30,
    sold: false,
    badge: "Auto · Patch · /199",
    img: "images/hart_front.jpg",
    back: "images/hart_back.jpg",
    slug: "hart"
  },
  {
    cat: ["autos"],
    name: "Cafu",
    detail: "Auto e Numerada a /25",
    club: "Brasil",
    numbered: true,
    set: "Leaf Metal",
    price: 45,
    sold: false,
    badge: "Auto · /25",
    img: "images/cafu_front.jpg",
    back: "images/cafu_back.jpg",
    slug: "cafu"
  },
  {
    cat: ["autos"],
    name: "Mascherano",
    detail: "Auto e Numerada a /250",
    club: "Argentina",
    numbered: true,
    set: "Topps Argentina Set 2024",
    price: 30,
    sold: false,
    badge: "Auto · /250",
    img: "images/masche_front.jpeg",
    back: "images/masche_back.jpeg",
    slug: "masche"
  },
  {
    cat: ["autos"],
    name: "Thomas Müller",
    detail: "Euro Masters · Auto e Numerada a /100",
    club: "Alemanha",
    numbered: true,
    set: "Topps Euro 2024",
    price: 40,
    sold: false,
    badge: "Auto · /100",
    img: "images/muller_front.jpg",
    back: "images/muller_back.jpg",
    slug: "muller"
  },
  {
    cat: ["autos"],
    name: "Eric Abidal",
    detail: "Auto e Numerada a /50",
    club: "Barcelona",
    numbered: true,
    set: "Topps Barcelona Set 2023-24",
    price: 40,
    sold: false,
    badge: "Auto · /50",
    img: "images/abidal_front.jpeg",
    back: "images/abidal_back.jpeg",
    slug: "abidal"
  },
  {
    cat: ["autos"],
    name: "Dibu Martínez",
    detail: "Auto e Numerada a /250",
    club: "Argentina",
    numbered: true,
    set: "Topps Argentina Set 2024",
    price: 25,
    sold: false,
    badge: "Auto · /250",
    img: "images/dibu_front.jpeg",
    back: "images/dibu_back.jpeg",
    slug: "dibu"
  },
  {
    cat: ["autos"],
    name: "Khedira",
    detail: "Auto e Numerada a /250",
    club: "Juventus",
    numbered: true,
    set: "Topps Juventus Set 2025",
    price: 20,
    sold: false,
    badge: "Auto · /250",
    img: "images/khedira_front.jpeg",
    back: "images/khedira_back.jpeg",
    slug: "khedira"
  },
  // PSA 
  {
    cat: ["psa"],
    name: "Lampard",
    detail: "PSA 8",
    club: "Chelsea",
    numbered: false,
    set: "Topps Icon 2022",
    price: 30,
    sold: false,
    badge: "PSA",
    img: "images/lampard_front.jpeg",
    back: "images/lampard_back.jpeg",
    slug: "lampard"
  },
  {
    cat: ["psa"],
    name: "Naomi",
    detail: "Auto · PSA 9 · Numerada a /175",
    club: "WWE",
    numbered: true,
    set: "Topps Chrome WWE 2025",
    price: 50,
    sold: false,
    badge: "Auto PSA · /175",
    img: "images/naomi_front.jpeg",
    back: "images/naomi_back.jpeg",
    slug: "naomi"
  },
  {
    cat: ["psa"],
    name: "Braun Strowman",
    detail: "PSA 9 · Numerada a /5",
    club: "WWE",
    numbered: true,
    set: "Topps Chrome WWE 2025",
    price: 50,
    sold: false,
    badge: "PSA · /5",
    img: "images/braun_front.jpeg",
    back: "images/braun_back.jpeg",
    slug: "braun"
  },
  {
    cat: ["psa"],
    name: "Becky Lynch",
    detail: "PSA 9 · Numerada a /150",
    club: "WWE",
    numbered: true,
    set: "Topps Chrome WWE 2025",
    price: 45,
    sold: false,
    badge: "PSA · /150",
    img: "images/becky_front.jpeg",
    back: "images/becky_back.jpeg",
    slug: "becky"
  },
  {
    cat: ["psa"],
    name: "Nia Jax",
    detail: "PSA 9 · Numerada a /99",
    club: "WWE",
    numbered: true,
    set: "Topps Chrome WWE 2025",
    price: 45,
    sold: false,
    badge: "PSA · /5",
    img: "images/nia_front.jpeg",
    back: "images/nia_back.jpeg",
    slug: "nia"
  },
  // PATCHES
  {
    cat: ["patches"],
    name: "Vitinha",
    detail: "Relic Card · Patch e Numerada a /299",
    club: "PSG",
    numbered: true,
    set: "Topps UCC Flagship 2024-25",
    price: 15,
    sold: false,
    badge: "Patch · /299",
    img: "images/vitinha_front.jpg",
    back: "images/vitinha_back.jpg",
    slug: "vitinha"
  },
  // PORTUGUESES
  {
    cat: ["portugueses"],
    name: "Rodrigo Mora",
    detail: "Rookie RC Skillset",
    club: "FC Porto",
    numbered: false,
    set: "Topps Finest UCC 2024-25",
    price: 10,
    sold: false,
    badge: "Rookie",
    img: "images/mora_front.jpg",
    back: "images/mora_back.jpg",
    slug: "mora"
  },
  {
    cat: ["portugueses"],
    name: "Geovany Quenda",
    detail: "Rookie RC Skillset · Numerada a /299",
    club: "Sporting CP",
    numbered: true,
    set: "Topps Finest UCC 2024-25",
    price: 15,
    sold: false,
    badge: "Rookie · /299",
    img: "images/quenda_front.jpg",
    back: "images/quenda_back.jpg",
    slug: "quenda"
  },
  // RONALDO
  {
    cat: ["ronaldo"],
    name: "Cristiano Ronaldo",
    detail: "Pitch Kings",
    club: "Portugal",
    numbered: false,
    set: "Panini Donruss FIFA 2023-24",
    price: 10,
    sold: false,
    badge: "CR7",
    img: "images/cr7pk_front.jpg",
    back: "images/cr7pk_back.jpg",
    slug: "cr7pk"
  },
  {
    cat: ["ronaldo"],
    name: "Cristiano Ronaldo",
    detail: "Magicians",
    club: "Portugal",
    numbered: false,
    set: "Panini Donruss FIFA 2024-25",
    price: 10,
    sold: false,
    badge: "CR7",
    img: "images/cr7mgc_front.jpg",
    back: "images/cr7mgc_back.jpg",
    slug: "cr7mgc"
  },
  {
    cat: ["ronaldo"],
    name: "Cristiano Ronaldo",
    detail: "Living Set",
    club: "Portugal",
    numbered: false,
    set: "Topps UEFA Euro 2024",
    price: 12,
    sold: false,
    badge: "CR7",
    img: "images/cr7ls_front.jpg",
    back: "images/cr7ls_back.jpg",
    slug: "cr7ls"
  },
  {
    cat: ["ronaldo"],
    name: "Cristiano Ronaldo",
    detail: "Gold Drip",
    club: "Juventus",
    numbered: false,
    set: "Topps Juventus Team Set 2024-25",
    price: 12,
    sold: false,
    badge: "CR7",
    img: "images/cr7gold_front.jpg",
    back: "images/cr7gold_back.jpg",
    slug: "cr7gd"
  },
  // YAMAL
  {
    cat: ["yamal"],
    name: "Lamine Yamal",
    detail: "Mystic Nights",
    club: "Barcelona",
    numbered: false,
    set: "Topps Merlin 2023-24",
    price: 20,
    sold: false,
    badge: "Rookie",
    img: "images/yamalmys_front.jpeg",
    back: "images/yamalmys_back.jpeg",
    slug: "yamalmys"
  },
  {
    cat: ["yamal"],
    name: "Lamine Yamal",
    detail: "Gold Drip",
    club: "Barcelona",
    numbered: false,
    set: "Topps Merlin 2023-24",
    price: 30,
    sold: false,
    badge: "Rookie",
    img: "images/yamalgold_front.jpeg",
    back: "images/yamalgold_back.jpeg",
    slug: "yamalgd"
  },
  {
    cat: ["yamal"],
    name: "Lamine Yamal",
    detail: "Kopa Trophy Winner",
    club: "Barcelona",
    numbered: false,
    set: "Topps Now",
    price: 25,
    sold: false,
    badge: "Rookie",
    img: "images/yamalkopa_front.jpeg",
    back: "images/yamalkopa_back.jpeg",
    slug: "yamalkopa"
  },
  {
    cat: ["yamal"],
    name: "Lamine Yamal",
    detail: "Prodigy",
    club: "Barcelona",
    numbered: false,
    set: "Topps Deco 2023-24",
    price: 20,
    sold: false,
    badge: "Rookie",
    img: "images/yamalprod_front.jpeg",
    back: "images/yamalprod_back.jpeg",
    slug: "yamalprod"
  },
  {
    cat: ["yamal"],
    name: "Lamine Yamal",
    detail: "Next",
    club: "Spain",
    numbered: false,
    set: "Futera Unique 2025",
    price: 15,
    sold: false,
    badge: "yamal",
    img: "images/yamalfut_front.jpeg",
    back: "images/yamalfut_back.jpeg",
    slug: "yamalfut"
  },
  {
    cat: ["yamal"],
    name: "Lamine Yamal",
    detail: "The Rookies",
    club: "Barcelona",
    numbered: false,
    set: "Paninni Donruss 2023-24",
    price: 20,
    sold: false,
    badge: "Rookie",
    img: "images/yamaldon_front.jpeg",
    back: "images/yamaldon_back.jpeg",
    slug: "yamalrook"
  },
  {
    cat: ["yamal"],
    name: "Lamine Yamal",
    detail: "Cover Stars",
    club: "Barcelona",
    numbered: false,
    set: "Topps UCC 2024-25",
    price: 20,
    sold: false,
    badge: "Rookie",
    img: "images/yamalcov_front.jpeg",
    back: "images/yamalcov_back.jpeg",
    slug: "yamalcov"
  },  
  // MESSI
  {
    cat: ["messi"],
    name: "Lionel Messi",
    detail: "Stadium Club Chrome",
    club: "PSG",
    numbered: false,
    set: "Topps Stadium Club Chrome 2022-23",
    price: 7,
    sold: false,
    badge: "Messi",
    img: "images/messistd_front.jpg",
    back: "images/messistd_back.jpg",
    slug: "messistd"
  },
  {
    cat: ["messi"],
    name: "Lionel Messi",
    detail: "Historic Captains",
    club: "Barcelona",
    numbered: false,
    set: "Topps UCC Flagship 2024-25",
    price: 8,
    sold: false,
    badge: "Messi",
    img: "images/messihc_front.jpg",
    back: "images/messihc_back.jpg",
    slug: "messihis"
  },
  {
    cat: ["messi"],
    name: "Lionel Messi",
    detail: "Gold Drip",
    club: "Barcelona",
    numbered: false,
    set: "Topps Barcelona Team Set 2024-25",
    price: 10,
    sold: false,
    badge: "Messi",
    img: "images/messigold_front.jpg",
    back: "images/messigold_back.jpg",
    slug: "messigd"
  },
  {
    cat: ["messi"],
    name: "Lionel Messi",
    detail: "Bona Fide Baller",
    club: "Argentina",
    numbered: false,
    set: "Topps Argentina Team Set 2024-25",
    price: 8,
    sold: false,
    badge: "Messi",
    img: "images/messibona_front.jpg",
    back: "images/messibona_back.jpg",
    slug: "messibona"
  },
  // PROJECT 22
  {
    cat: ["project22"],
    name: "Wayne Rooney",
    detail: "Topps Project 22",
    club: "Manchester United",
    numbered: false,
    set: "Topps Project 22",
    price: 12,
    sold: false,
    badge: "Project 22",
    img: "images/rooneyp22_front.jpg",
    back: "images/rooneyp22_back.jpg",
    slug: "rooneyp22"
  },
  {
    cat: ["project22"],
    name: "Erling Haaland",
    detail: "Topps Project 22",
    club: "Manchester City",
    numbered: false,
    set: "Topps Project 22",
    price: 12,
    sold: true,
    badge: "Project 22",
    img: "images/haalandp22_front.jpg",
    back: "images/haalandp22_back.jpg",
    slug: "haalandp22"
  },
  {
    cat: ["project22"],
    name: "Andrés Iniesta",
    detail: "Topps Project 22",
    club: "Barcelona",
    numbered: false,
    set: "Topps Project 22",
    price: 14,
    sold: false,
    badge: "Project 22",
    img: "images/iniestap22_front.jpg",
    back: "images/iniestap22_back.jpg",
    slug: "iniestap22"
  },
  {
    cat: ["project22"],
    name: "Jude Bellingham",
    detail: "Topps Project 22",
    club: "Borussia Dortmund",
    numbered: false,
    set: "Topps Project 22",
    price: 10,
    sold: true,
    badge: "Project 22",
    img: "images/judep22_front.jpg",
    back: "images/judep22_back.jpg",
    slug: "judep22"
  },
  {
    cat: ["project22"],
    name: "Frank Lampard",
    detail: "Topps Project 22",
    club: "Chelsea",
    numbered: false,
    set: "Topps Project 22",
    price: 12,
    sold: false,
    badge: "Project 22",
    img: "images/lampardp22_front.jpg",
    back: "images/lampardp22_back.jpg",
    slug: "lampardp22"
  },
  {
    cat: ["project22"],
    name: "Paolo Maldini",
    detail: "Topps Project 22",
    club: "AC Milan",
    numbered: false,
    set: "Topps Project 22",
    price: 12,
    sold: true,
    badge: "Project 22",
    img: "images/maldinip22_front.jpg",
    back: "images/maldinip22_back.jpg",
    slug: "maldinip22"
  },
  // RONALDINHO
  {
    cat: ["ronaldinho"],
    name: "Ronaldinho",
    detail: "Joueur Emblématique",
    club: "Barcelona",
    numbered: false,
    set: "Topps Argentina Team Set 2024-25",
    price: 8,
    sold: false,
    badge: "Ronaldinho",
    img: "images/r10jou_front.jpg",
    back: "images/r10jou_back.jpg",
    slug: "r10jou"
  },
  {
    cat: ["ronaldinho"],
    name: "Ronaldinho",
    detail: "Gold Drip",
    club: "Barcelona",
    numbered: false,
    set: "Topps Barcelona Team Set 2024-25",
    price: 8,
    sold: false,
    badge: "Ronaldinho",
    img: "images/r10gold_front.jpg",
    back: "images/r10gold_back.jpg",
    slug: "r10gd"
  },
  {
    cat: ["ronaldinho"],
    name: "Ronaldinho",
    detail: "First Goal",
    club: "Barcelona",
    numbered: false,
    set: "Topps Barcelona Team Set 2024-25",
    price: 10,
    sold: false,
    badge: "Ronaldinho",
    img: "images/r10bar_front.jpg",
    back: "images/r10bar_back.jpg",
    slug: "r10first"
  },
  // RONALDO FENOMENO
  {
    cat: ["fenomeno"],
    name: "Ronaldo Fenómeno",
    detail: "Gold Drip",
    club: "Barcelona",
    numbered: false,
    set: "Topps Barcelona Team Set 2024-25",
    price: 10,
    sold: false,
    badge: "R. Fenómeno",
    img: "images/r9gold_front.jpg",
    back: "images/r9gold_back.jpg",
    slug: "r9gd"
  },
  {
    cat: ["fenomeno"],
    name: "Ronaldo Fenómeno",
    detail: "Topps UEFA 59'",
    club: "Barcelona",
    numbered: false,
    set: "Topps UEFA 59' 2022-23",
    price: 8,
    sold: false,
    badge: "R. Fenómeno",
    img: "images/r959_front.jpg",
    back: "images/r959_back.jpg",
    slug: "r959"
  },
  {
    cat: ["fenomeno"],
    name: "Ronaldo Fenómeno",
    detail: "Topps Barcelona Team Set",
    club: "Barcelona",
    numbered: false,
    set: "Topps Barcelona Team Set 2023-24",
    price: 6,
    sold: false,
    badge: "R. Fenómeno",
    img: "images/r9bar_front.jpg",
    back: "images/r9bar_front.jpg",
    slug: "r9team"
  },
  // ROOKIES
  {
    cat: ["rookies"],
    name: "Myles Lewis-Skelly",
    detail: "Rookie RC Saphire",
    club: "Arsenal",
    numbered: false,
    set: "Topps Chrome UCC 2024-25",
    price: 10,
    sold: false,
    badge: "Rookie",
    img: "images/skelly_front.jpg",
    back: "images/skelly_back.jpg",
    slug: "myles"
  },
  {
    cat: ["rookies"],
    name: "Tijani Reijnders",
    detail: "Rookie RC Winter Camo · Numerada a /30",
    club: "AC Milan",
    numbered: true,
    set: "Panini Select FIFA 2023-24",
    price: 15,
    sold: false,
    badge: "Rookie · /30",
    img: "images/reij_front.jpg",
    back: "images/reij_back.jpg",
    slug: "reijneiders"
  },
  {
    cat: ["rookies"],
    name: "Arda Güler",
    detail: "Rookie Kings RC",
    club: "Real Madrid",
    numbered: false,
    set: "Panini Donruss 2023-24",
    price: 5,
    sold: false,
    badge: "Rookie",
    img: "images/guler_front.jpg",
    back: "images/guler_back.jpg",
    slug: "guler"
  },
  {
    cat: ["rookies"],
    name: "Bradley Barcola",
    detail: "Rookie RC Paralela",
    club: "PSG",
    numbered: false,
    set: "Topps Flagship UCC 2024-25",
    price: 5,
    sold: false,
    badge: "Rookie",
    img: "images/barcola_front.jpg",
    back: "images/barcola_back.jpg",
    slug: "barcola"
  },
  {
    cat: ["rookies"],
    name: "Endrick",
    detail: "Rookie RC Wonderkids",
    club: "Real Madrid",
    numbered: false,
    set: "Topps Chrome UCC 2024-25",
    price: 5,
    sold: false,
    badge: "Rookie",
    img: "images/endrickwon_front.jpg",
    back: "images/endrickwon_back.jpg",
    slug: "endrickwon"
  },
  // LENDAS
  {
    cat: ["lendas"],
    name: "Juan Román Riquelme",
    detail: "The Greats",
    club: "Argentina",
    numbered: false,
    set: "Futera Unique 2023",
    price: 10,
    sold: false,
    badge: "Lenda",
    img: "images/riquelme_front.jpg",
    back: "images/riquelme_back.jpg",
    slug: "riquelme"
  },
  {
    cat: ["lendas"],
    name: "Romário",
    detail: "Tribute",
    club: "Barcelona",
    numbered: false,
    set: "Topps Barcelona 125º Aniversário 2025",
    price: 8,
    sold: false,
    badge: "Lenda",
    img: "images/romario_front.jpg",
    back: "images/romario_back.jpg",
    slug: "romario"
  },
  {
    cat: ["lendas"],
    name: "Eric Cantona",
    detail: "Numerada a /75",
    club: "Manchester United",
    numbered: true,
    set: "Topps Total Football",
    price: 15,
    sold: false,
    badge: "Lenda · /75",
    img: "images/cantona_front.jpg",
    back: "images/cantona_back.jpg",
    slug: "cantona"
  },
  {
    cat: ["lendas"],
    name: "Roberto Baggio",
    detail: "Artistry",
    club: "Juventus",
    numbered: false,
    set: "Topps Deco UCC 2025-26",
    price: 8,
    sold: false,
    badge: "Lenda",
    img: "images/baggio_front.jpg",
    back:  "images/baggio_back.jpg",
    slug: "baggio"
  },
  {
    cat: ["lendas"],
    name: "Paul Scholes",
    detail: "Legacy",
    club: "Manchester United",
    numbered: false,
    set: "Topps Inception UEFA 2023-24",
    price: 8,
    sold: false,
    badge: "Lenda",
    img: "images/scholes_front.jpg",
    back: "images/scholes_back.jpg",
    slug: "scholes"
  },
  {
    cat: ["lendas"],
    name: "Zinedine Zidane",
    detail: "Cheat Code",
    club: "França",
    numbered: false,
    set: "Topps Chrome UEFA Euro 2024",
    price: 8,
    sold: false,
    badge: "Lenda",
    img: "images/zidane_front.jpg",
    back: "images/zidane_back.jpg",
    slug: "zidane"
  },
  {
    cat: ["lendas"],
    name: "Lothar Matthäus",
    detail: "Pioneer · Numerada a /99",
    club: "Bayern Munich",
    numbered: true,
    set: "Topps Decades 1990's",
    price: 15,
    sold: true,
    badge: "Lenda · /99",
    img: "images/matthaus_front.jpg",
    back: "images/matthaus_back.jpg",
    slug: "matthaus"
  },
  {
    cat: ["lendas"],
    name: "Sérgio Agüero",
    detail: "Bluemoon · Numerada a /99",
    club: "Manchester City",
    numbered: true,
    set: "Topps Manchester City Set 2024",
    price: 12,
    sold: false,
    badge: "Lenda · /99",
    img: "images/aguero_front.jpg",
    back: "images/aguero_back.jpg",
    slug: "aguero"
  },
  // NBA
  {
    cat: ["nba"],
    name: "Baron Davis",
    detail: "Court Kings · Match-worn Patch",
    club: "New Orleans Hornets",
    numbered: false,
    set: "NBA Fleer 2002-03",
    price: 8,
    sold: false,
    badge: "NBA Patch",
    img: "images/baron_front.jpg",
    back: "images/baron_back.jpg",
    slug: "baron"
  },
  // UFC
  {
    cat: ["ufc"],
    name: "Conor McGregor",
    detail: "Season Ticket · Numerada a /99",
    club: "UFC",
    numbered: true,
    set: "UFC Panini 2021",
    price: 10,
    sold: false,
    badge: "UFC · /99",
    img: "images/conor_front.jpg",
    back: "images/conor_back.jpg",
    slug: "conor"
  },
  {
    cat: ["ufc"],
    name: "Nate Diaz",
    detail: "Rookies Stars",
    club: "UFC",
    numbered: true,
    set: "UFC Panini 2021",
    price: 5,
    sold: false,
    badge: "UFC",
    img: "images/nate_front.jpg",
    back: "images/nate_back.jpg",
    slug: "nate"
  },
  // DIVERSAS
  {
    cat: ["diversas"],
    name: "R2-D2 Resistance",
    detail: "Star Wars",
    club: "Star Wars",
    numbered: false,
    set: "Star Wars Topps Chrome",
    price: 7,
    sold: false,
    badge: "Star Wars",
    img: "images/r2d2_front.jpg",
    back: "images/r2d2_back.jpg",
    slug: "r2d2"
  }
];
